---
config:
  flowchart:
    curve: linear
---
graph LR;
	skills(skills)
	model(model)
	tools(tools)
	summarize(summarize)
	model --> summarize;
	model --> tools;
	skills --> model;
	tools --> model;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
