---
config:
  flowchart:
    curve: linear
---
graph LR;
	skill_context(skill_context)
	prep_stage(prep_stage)
	query_stage(query_stage)
	save(save)
	answer(answer)
	prep_stage --> answer;
	prep_stage --> query_stage;
	query_stage --> answer;
	query_stage --> save;
	save --> answer;
	skill_context --> prep_stage;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
