---
config:
  flowchart:
    curve: linear
---
graph LR;
	suggest(suggest)
	clarify(clarify)
	inspect(inspect)
	plan(plan)
	execute(execute)
	repair(repair)
	execute --> repair;
	inspect --> plan;
	plan --> execute;
	repair --> plan;
	suggest --> clarify;
	suggest --> inspect;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
