---
config:
  flowchart:
    curve: linear
---
graph LR;
	skills(skills)
	prep(prep)
	sql(sql)
	validate(validate)
	save(save)
	package(package)
	prep --> package;
	prep --> sql;
	save --> package;
	skills --> prep;
	sql --> package;
	sql --> validate;
	validate --> package;
	validate --> save;
	validate --> sql;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
